# Taken and adapted from test-OSW.yml which is part of Open-Smartwatch-OS
# Link: https://github.com/Open-Smartwatch/open-smartwatch-os/blob/master/.github/workflows/test-OSW.yml

name: Build Minty-OS (Ubuntu, all models)

on:
  workflow_dispatch:
  push:
    paths_ignore: '["*.md"]'
  pull_request:
    branches: [ main ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  build-os:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository and submodules
        # uses: actions/checkout@v3 # incompatible with git lfs cache bandwidth calcs (https://github.com/actions/checkout/issues/165)
        uses: nschloe/action-cached-lfs-checkout@v1.2.1
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: platformio-${{ runner.os }}
      - name: Install swig
        run: sudo apt-get update && sudo apt-get -y install swig
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PlatformIO
        run: python -m pip install --upgrade pip && pip install --upgrade platformio
      - name: Rename config
        run: mv include/config.h.example include/config.h
      - name: Compile language ${{ matrix.language }} model ${{ matrix.model }}
        run: pio run -ewatchy
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmwares
          path: |
            *.bin
